version: "3.9"
services:
  neo4j:
    container_name: "sand_mine_neo4j_container"
    ports:
      - 7474:7474
      - 7687:7687
    build:
      context: .
      dockerfile: "./dockerfile-neo4j"
    volumes:
      - "/shared/tmp:/shared/tmp"

  backend:
    container_name: "sand_mine_backend_container"
    ports:
      - 8080:8080
    build:
      context: .
      dockerfile: "./dockerfile-backend"
    volumes:
      - "/shared/tmp:/shared/tmp"

  frontend:
    container_name: "sand_mine_frontend_container"
    ports:
      - 8000:8000
    build:
      context: .
      dockerfile: "./dockerfile-frontend"